### ISSUE TITLE
'attach_hush_to' script fails to mount sdcard

### ISSUE THREAD

**Issue by n1ete** [19hundreds/risks-workflow#5]
first i wanna say thanks for the whole awesome R.I.S.K.S. writeup!
i run into a problem when trying to mount the block device in dom0 to my-vault

```
user@dom0$ attach_hush_to my-vault

Block sys-usb:sda is currently attached to ()
Please umount it properly from there and rerun this program.
```
as far as i can say its not mounted to anything (maybe i missed something here?)
looking at the attach-hush-script and entered in dom0

```
qvm-block list | grep sys-usb:sda | awk {'print $3'} | cut -d"  " -f1
```
throws a `()` back...?

any help how to fix this?

thanks in advance ;)

**Comment by 19hundreds** [comment]
Sorry for the delayed reply and thank you for the appreciation.

Maybe you already solved the problem however it feels like you have a faulty sdcard or your sys-usb qube has some (possibly temporary) troubles. Basically dom0 has registered your hush partition as already attached to something that now is not existing anymore (did you rename any qube?)

A couple times I experienced some weird behavior in my sys-usb similar to yours too. In my case they seemed to be due to my usb keyboard messing up with sys-usb.

I know it might look strange but did you try reboot sys-usb and/or you dom0, then plug in the least amount of USB devices possible and try it again.

BTW are you running Qubes R4.0?

**Comment by n1ete** [comment]
Hey thanks for your hints, didnt had time to test it further yet but will report back asap...
jepp, i am on qubes 4.0

**Comment by n1ete** [comment]
so, gave it another try and spinned up another clean standalone qube, this time from a fedora template and ran into the exactly same problem.
qvm-block gives me:
```
sys-usb:sda ()
sys-usb:sda1 (DATA)
sys-usb:sda2 ()
```
i append this line in my .bashrc 
`export SDCARD_BLOCK="sys-usb:sda2"`

rebooting the usb-qubes/dom0 didnt change that behaviour.
every step worked perfectly till to this point and didnt run in any errors.
i am using btrfs on qubes btw.

**Comment by n1ete** [comment]
just wanted to report that everything is working fine since i did a fresh qubes install...on ext4 this time though so still not sure if it was btrfs related or just a misconfiguration.
thanks again for this concept! some updates are needed though, the master key generation could be better i think and pass is also out in v 1.7.3 ;)
i close this anyways

**Comment by 19hundreds** [comment]
thanks @n1ete  for your report. I was wondering if you ever found a solution.

Now that you mention btrfs I think that the issue could be related to udev rules. I've no experience with btrfs but it seems like your dom0 used a naming different than usual (maybe because of some udev rules??) which the qvm-block couldn't handle and therefore you couldn't attach the sdcard to vault.

You are right when you say that RISKS is starting being a little outdated. I even have more pages to add about wallets and custom tombs. Unfortunately I simply don't have enough time and I'm currently spending time in deploying a "decent enough" chat system "decently safe and private" for everyone.

Maybe you feel like giving me a hand in something I'm doing?

**Comment by n1ete** [comment]
Time is aswell an limited factor these days, but i would love to help! i will try to create the pull requests for both suggestions as a little git exercise for myself then ;) are there some features you wanna implement already?

**Comment by 19hundreds** [comment]
yes, time - so rare that's why the most precious thing

I added you to the Gitter room [RISKS-workflow](https://gitter.im/RISKS-workflow/community). The first thing would be to review the text that is already present searching for mistakes or potentially dangerous "copy and paste" text. I've noticed that there are parts where a distracted user could fall. Basically I'm looking for improvement in first place. Then there are the new features to be documented (I already tested them) like custom-tomb files, split wallets and bisq
